// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-083JPGdB_wk3rbq2BsLi9btvewLoOSw',
    appId: '1:944506937258:web:fb2bae99df53848e6695d3',
    messagingSenderId: '944506937258',
    projectId: 'flutterchatapp-a9dc9',
    authDomain: 'flutterchatapp-a9dc9.firebaseapp.com',
    storageBucket: 'flutterchatapp-a9dc9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-MPUD__n4WMjWkQvAfPL7okRNbiGnJqs',
    appId: '1:944506937258:android:551d07690558dc0f6695d3',
    messagingSenderId: '944506937258',
    projectId: 'flutterchatapp-a9dc9',
    storageBucket: 'flutterchatapp-a9dc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYOGPbO8SP6aQRoAxz3fXRv68nUT5-6jU',
    appId: '1:944506937258:ios:b489b659b27e64876695d3',
    messagingSenderId: '944506937258',
    projectId: 'flutterchatapp-a9dc9',
    storageBucket: 'flutterchatapp-a9dc9.appspot.com',
    iosBundleId: 'com.example.flutterLiveChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYOGPbO8SP6aQRoAxz3fXRv68nUT5-6jU',
    appId: '1:944506937258:ios:b489b659b27e64876695d3',
    messagingSenderId: '944506937258',
    projectId: 'flutterchatapp-a9dc9',
    storageBucket: 'flutterchatapp-a9dc9.appspot.com',
    iosBundleId: 'com.example.flutterLiveChat',
  );
}
